name: calculadora_grupal
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  math_expressions: ^2.5.0
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  intl: ^0.19.0

flutter:
  fonts:
    - family: Arial
      fonts:
        - asset: fonts/Arial.ttf

  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
